#include "resolve.h"

#include <algorithm>
#include <cmath>
#include <limits>
#include "pcl_conversions/pcl_conversions.h"
#include "pcl/point_cloud.h"
#include "pcl/point_types.h"

#define TDT_INFO(msg) std::cout << msg << std::endl

namespace tdt_radar {

float Resolve::convert_parsed_y(float parsed_y, bool use_legacy_plus) const
{
    if (use_legacy_plus) {
        return arena_height_ + parsed_y;
    }
    return arena_height_ - parsed_y;
}

Resolve::Resolve(const rclcpp::NodeOptions& node_options)
    : Node("radar_resolve_node", node_options)
{
    const auto map_points_path =
        this->declare_parameter<std::string>("map_points",
                                             "./config/map/map_points.yaml");
    const auto camera_params_path =
        this->declare_parameter<std::string>("camera_params",
                                             "./config/camera_params.yaml");
    const auto out_matrix_path = this->declare_parameter<std::string>(
        "out_matrix", "./config/out_matrix.yaml");
    (void)this->declare_parameter<std::string>("map_image", "config/map/map.jpg");
    arena_width_ = this->declare_parameter<float>("map_width", 28.0F);
    arena_height_ = this->declare_parameter<float>("map_height", 15.0F);
    detect_use_legacy_plus_y_ =
        this->declare_parameter<bool>("detect_use_legacy_plus_y", true);
    pixel_scale_x_ =
        this->declare_parameter<float>("pixel_scale_x", 1.0F);
    pixel_scale_y_ =
        this->declare_parameter<float>("pixel_scale_y", 1.0F);
    const auto map_points_referee_frame =
        this->declare_parameter<bool>("map_points_referee_frame", true);
    parser_ = std::make_unique<parser>(map_points_path, camera_params_path,
                                       out_matrix_path, arena_height_,
                                       map_points_referee_frame);
    const cv::Point3f cam_pos = parser_->camera_world_pos();
    RCLCPP_INFO(this->get_logger(),
                "Resolve calibration: out_matrix=%s camera_world=(%.2f, %.2f, %.2f)",
                out_matrix_path.c_str(), cam_pos.x, cam_pos.y, cam_pos.z);
    // Optional 3-D field mesh for ray casting (replaces flat-plane assumption).
    // Generate with: python tools/gen_field_mesh.py
    // HeightGrid: O(1) fast path (preferred, generated by tools/gen_field_mesh.py)
    const auto grid_path = this->declare_parameter<std::string>(
        "field_grid_path", "config/map/field_mesh.bin");
    if (!grid_path.empty()) {
        if (parser_->load_grid(grid_path))
            RCLCPP_INFO(this->get_logger(),
                        "Field height grid loaded: %s", grid_path.c_str());
        else
            RCLCPP_WARN(this->get_logger(),
                        "HeightGrid not loaded: %s", grid_path.c_str());
    }
    // MeshRaycaster: fallback for arbitrary PLY (Möller-Trumbore)
    const auto mesh_path = this->declare_parameter<std::string>(
        "field_mesh_path", "");
    if (!mesh_path.empty()) {
        if (parser_->load_mesh(mesh_path))
            RCLCPP_INFO(this->get_logger(),
                        "Field mesh loaded: %s", mesh_path.c_str());
        else
            RCLCPP_WARN(this->get_logger(),
                        "Failed to load field mesh: %s",
                        mesh_path.c_str());
    }
    point_sub = this->create_subscription<geometry_msgs::msg::Vector3>(
        "camera_point2D", rclcpp::SensorDataQoS(),
        std::bind(&Resolve::callback, this, std::placeholders::_1));

    pub = this->create_publisher<sensor_msgs::msg::PointCloud2>(
        "camera_point3D", rclcpp::SensorDataQoS());
    detect_sub =
        this->create_subscription<vision_interface::msg::DetectResult>(
            "detect_result", rclcpp::SensorDataQoS(),
            std::bind(&Resolve::DetectCallback, this,
                      std::placeholders::_1));
    pub_radar = this->create_publisher<vision_interface::msg::DetectResult>(
        "resolve_result", rclcpp::SensorDataQoS());
    frustum_pixel_gate_ = this->declare_parameter<float>("frustum_pixel_gate", 50.0F);
    // Camera-primary by default: 3D-box-validated camera positions are accurate;
    // LiDAR cluster (sparse Mid-70 + over-segmentation on field structures) is
    // noisy. cam_bias EMA still learns systematic offsets when LiDAR and
    // camera agree within 0.8m gate.
    lidar_calibrate_camera_  = this->declare_parameter<bool>("lidar_calibrate_camera", true);
    cam_bias_alpha_          = this->declare_parameter<float>("cam_bias_alpha", 0.05F);
    lidar_consistency_gate_  = this->declare_parameter<float>("lidar_consistency_gate", 0.8F);
    RCLCPP_INFO(this->get_logger(),
                "Resolve fusion: calibrate_camera=%s  consistency_gate=%.2fm  bias_alpha=%.3f",
                lidar_calibrate_camera_ ? "ON" : "OFF",
                lidar_consistency_gate_, cam_bias_alpha_);
    cluster_sub_ = this->create_subscription<sensor_msgs::msg::PointCloud2>(
        "/livox/lidar_cluster", rclcpp::SensorDataQoS(),
        std::bind(&Resolve::ClusterCallback, this, std::placeholders::_1));
    TDT_INFO("Load radar resolve node success!");
}

void Resolve::callback(const geometry_msgs::msg::Vector3::SharedPtr msg)
{
    if (!parser_) return;
    cv::Point2f point;
    point.x = msg->x;
    point.y = msg->y;
    auto center_point = parser_->parse(point);
    if (!std::isfinite(center_point.x) || !std::isfinite(center_point.y)) return;
    center_point.y = convert_parsed_y(center_point.y, detect_use_legacy_plus_y_);
    pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(
        new pcl::PointCloud<pcl::PointXYZ>);
    pcl::PointXYZ send_point;
    send_point.x = center_point.x;
    send_point.y = center_point.y;
    send_point.z = 1;
    cloud->points.push_back(send_point);
    sensor_msgs::msg::PointCloud2 output;
    pcl::toROSMsg(*cloud, output);
    output.header.frame_id = "rm_frame";
    pub->publish(output);
}

void Resolve::ClusterCallback(const sensor_msgs::msg::PointCloud2::SharedPtr msg)
{
    pcl::PointCloud<pcl::PointXYZ> cloud;
    pcl::fromROSMsg(*msg, cloud);
    std::lock_guard<std::mutex> lk(cluster_mu_);
    latest_clusters_.clear();
    latest_clusters_.reserve(cloud.size());
    for (const auto& pt : cloud.points)
        latest_clusters_.push_back({pt.x, pt.y});
}

void Resolve::DetectCallback(
    const vision_interface::msg::DetectResult::SharedPtr msg)
{
    if (!parser_) {
        RCLCPP_ERROR_THROTTLE(this->get_logger(), *this->get_clock(), 5000,
                              "parser_ is null, cannot resolve coordinates");
        return;
    }

    auto clamp_field = [this](cv::Point2f p) {
        p.x = std::clamp(p.x, 0.0F, arena_width_);
        p.y = std::clamp(p.y, 0.0F, arena_height_);
        return p;
    };

    // ── Step 1: camera pixel → world for all detections ──────────────────────
    // Keep raw pixel coords (in detect_result units) for frustum matching below.
    struct Slot {
        float raw_x, raw_y;  // box center (original image pixels)
        float box_w, box_h;  // bounding box dimensions
        cv::Point2f world; bool valid = false;
    };

    // Near-edge correction: bbox bottom pixel hits the chassis corner nearest to
    // the camera on the ground. The true robot centre is ~HALF_CHASSIS further
    // away from the camera in the XY plane. Apply before convert_parsed_y since
    // camera_world_pos() is in the same frame as parse() output.
    static constexpr float HALF_CHASSIS = 0.26f;  // m, ½ typical RM infantry depth
    const cv::Point3f cam_pos = parser_->camera_world_pos();
    auto apply_chassis_offset = [&](cv::Point2f& cp) {
        float dx = cp.x - cam_pos.x;
        float dy = cp.y - cam_pos.y;
        float dist = std::sqrt(dx * dx + dy * dy);
        if (dist > 0.5f) {   // only apply when robot is not directly below camera
            cp.x += HALF_CHASSIS * dx / dist;
            cp.y += HALF_CHASSIS * dy / dist;
        }
    };

    Slot blue_slots[kRobotSlotCount], red_slots[kRobotSlotCount];
    for (int i = 0; i < kRobotSlotCount; i++) {
        blue_slots[i].raw_x = msg->blue_x[i];
        blue_slots[i].raw_y = msg->blue_y[i];
        blue_slots[i].box_w = msg->blue_w[i];
        blue_slots[i].box_h = msg->blue_h[i];
        cv::Point2f bp(msg->blue_x[i] * pixel_scale_x_, msg->blue_y[i] * pixel_scale_y_);
        if (bp.x * bp.y) {
            auto cp = parser_->parse(bp, slot_to_robot_number(i));
            if (std::isfinite(cp.x) && std::isfinite(cp.y)) {
                apply_chassis_offset(cp);
                cp.y = convert_parsed_y(cp.y, detect_use_legacy_plus_y_);
                blue_slots[i].world = clamp_field(cp);
                blue_slots[i].valid = true;
            }
        }
        red_slots[i].raw_x = msg->red_x[i];
        red_slots[i].raw_y = msg->red_y[i];
        red_slots[i].box_w = msg->red_w[i];
        red_slots[i].box_h = msg->red_h[i];
        cv::Point2f rp(msg->red_x[i] * pixel_scale_x_, msg->red_y[i] * pixel_scale_y_);
        if (rp.x * rp.y) {
            auto cp = parser_->parse(rp, slot_to_robot_number(i));
            if (std::isfinite(cp.x) && std::isfinite(cp.y)) {
                apply_chassis_offset(cp);
                cp.y = convert_parsed_y(cp.y, detect_use_legacy_plus_y_);
                red_slots[i].world = clamp_field(cp);
                red_slots[i].valid = true;
            }
        }
    }

    // ── Step 2: Frustum snapping / camera-primary EMA calibration ────────────
    //
    // lidar_calibrate_camera_=false (default, legacy):
    //   LiDAR cluster replaces camera estimate entirely.
    //
    // lidar_calibrate_camera_=true (camera-primary mode):
    //   When a LiDAR cluster matches a detection, update a global EMA bias:
    //     cam_bias = EMA(lidar_pos - camera_pos)
    //   Output is always camera_pos + cam_bias (camera drives position;
    //   LiDAR only teaches the systematic calibration offset).
    //   Slots with no LiDAR match also benefit via the accumulated bias.
    if (parser_->extrinsics_valid()) {
        std::vector<cv::Point2f> clusters;
        { std::lock_guard<std::mutex> lk(cluster_mu_); clusters = latest_clusters_; }
        if (!clusters.empty()) {
            const auto cluster_pixels =
                parser_->world_to_pixels(clusters, 0.15F);  // ARMOR_HEIGHT
            std::vector<bool> used(clusters.size(), false);
            for (int pass = 0; pass < 2; ++pass) {  // 0=blue, 1=red
                Slot* slots = (pass == 0) ? blue_slots : red_slots;
                for (int i = 0; i < kRobotSlotCount; ++i) {
                    if (!slots[i].valid) continue;
                    const float bw = slots[i].box_w;
                    const float bh = slots[i].box_h;
                    const float half_w = (bw > 0.f) ? bw * 0.5f + frustum_pixel_gate_ * 0.25f
                                                     : frustum_pixel_gate_;
                    const float half_h = (bh > 0.f) ? bh * 0.5f + frustum_pixel_gate_ * 0.25f
                                                     : frustum_pixel_gate_;
                    float best_d = std::numeric_limits<float>::infinity();
                    int   best_j = -1;
                    for (int j = 0; j < (int)clusters.size(); ++j) {
                        if (used[j]) continue;
                        const cv::Point2f& pix = cluster_pixels[j];
                        if (pix.x < 0.f) continue;
                        const float dx = pix.x - slots[i].raw_x;
                        const float dy = pix.y - slots[i].raw_y;
                        if (std::abs(dx) > half_w || std::abs(dy) > half_h) continue;
                        const float d = std::sqrt(dx * dx + dy * dy);
                        if (d < best_d) { best_d = d; best_j = j; }
                    }
                    if (best_j >= 0) {
                        const cv::Point2f lidar_pos = {clusters[best_j].x, clusters[best_j].y};
                        // Consistency check: large disagreement → cluster likely mis-matched
                        const float cdx   = lidar_pos.x - slots[i].world.x;
                        const float cdy   = lidar_pos.y - slots[i].world.y;
                        const float cdist = std::sqrt(cdx * cdx + cdy * cdy);
                        const bool  consistent = (lidar_consistency_gate_ <= 0.f)
                                                 || (cdist < lidar_consistency_gate_);
                        if (lidar_calibrate_camera_) {
                            // EMA bias updated ONLY when LiDAR and camera agree
                            if (consistent) {
                                const float alpha = (cam_bias_samples_ < 20)
                                    ? 1.0F / (cam_bias_samples_ + 1)  // warm-up: running mean
                                    : cam_bias_alpha_;                 // steady: EMA
                                cam_bias_.x = (1.f - alpha) * cam_bias_.x + alpha * cdx;
                                cam_bias_.y = (1.f - alpha) * cam_bias_.y + alpha * cdy;
                                ++cam_bias_samples_;
                            }
                            // Output is always camera-based (bias applied after this block)
                        } else {
                            // Legacy: LiDAR replaces camera only when consistent
                            if (consistent) slots[i].world = lidar_pos;
                            // else: keep camera estimate (cluster mis-match)
                        }
                        used[best_j] = true;  // mark used even if inconsistent
                    }
                }
            }
        }
    }
    // Camera-primary mode: apply accumulated bias to ALL valid camera slots
    if (lidar_calibrate_camera_ && cam_bias_samples_ > 0) {
        for (int pass = 0; pass < 2; ++pass) {
            Slot* slots = (pass == 0) ? blue_slots : red_slots;
            for (int i = 0; i < kRobotSlotCount; ++i) {
                if (!slots[i].valid) continue;
                slots[i].world.x += cam_bias_.x;
                slots[i].world.y += cam_bias_.y;
                slots[i].world = clamp_field(slots[i].world);
            }
        }
        RCLCPP_INFO_THROTTLE(this->get_logger(), *this->get_clock(), 5000,
            "cam_bias=(%.3f, %.3f) samples=%d",
            cam_bias_.x, cam_bias_.y, cam_bias_samples_);
    }

    // ── Step 3: publish results ───────────────────────────────────────────────
    vision_interface::msg::DetectResult     send_data;
    pcl::PointCloud<pcl::PointXYZRGBA>::Ptr cloud(
        new pcl::PointCloud<pcl::PointXYZRGBA>);
    for (int i = 0; i < kRobotSlotCount; i++) {
        if (blue_slots[i].valid) {
            send_data.blue_x[i] = blue_slots[i].world.x;
            send_data.blue_y[i] = blue_slots[i].world.y;
            send_data.blue_bot_id[i] = msg->blue_bot_id[i];
            pcl::PointXYZRGBA sp; sp.x=blue_slots[i].world.x; sp.y=blue_slots[i].world.y;
            sp.z=1; sp.r=0; sp.g=0; sp.b=255; sp.a=255;
            cloud->points.push_back(sp);
        }
        if (red_slots[i].valid) {
            send_data.red_x[i] = red_slots[i].world.x;
            send_data.red_y[i] = red_slots[i].world.y;
            send_data.red_bot_id[i] = msg->red_bot_id[i];
            pcl::PointXYZRGBA sp; sp.x=red_slots[i].world.x; sp.y=red_slots[i].world.y;
            sp.z=1; sp.r=255; sp.g=0; sp.b=0; sp.a=255;
            cloud->points.push_back(sp);
        }
    }

    send_data.header.stamp = msg->header.stamp;
    pub_radar->publish(send_data);
    auto cloud_msg = sensor_msgs::msg::PointCloud2();
    pcl::toROSMsg(*cloud, cloud_msg);
    cloud_msg.header.frame_id = "rm_frame";
    cloud_msg.header.stamp = msg->header.stamp;
    pub->publish(cloud_msg);
}
}  // namespace tdt_radar
RCLCPP_COMPONENTS_REGISTER_NODE(tdt_radar::Resolve)
