#!/bin/sh
### BEGIN INIT INFO
# Provides:          FGDriverServer
# Required-Start:    $remote_fs $syslog $local_fs
# Required-Stop:     $remote_fs $syslog $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: driver self-starting
# Description:       FGDriverServer is a daemon to self-starting driver server.
### END INIT INFO

SDK_HOME=${MVCAM_SDK_PATH}
KERNEL_VERSION=$(uname -r)

# Start the Driver Server
start() 
{
        INSTALL_KERNEL_VERSION=$(cat $SDK_HOME/driver/kernel_version)
        if [ "${KERNEL_VERSION}" != "${INSTALL_KERNEL_VERSION}" ]; then #内核版本不匹配，删除ko文件重新编译
                echo "Current kernel version:${KERNEL_VERSION}, Kernel version when install driver last time:${INSTALL_KERNEL_VERSION}"
                #记录当前内核版本信息
                echo "${KERNEL_VERSION}" > $SDK_HOME/driver/kernel_version
                rm $SDK_HOME/driver/pcie/*.ko -rf
        fi

        if [ -f $SDK_HOME/driver/pcie/build.sh ]; then
                bash $SDK_HOME/driver/pcie/build.sh >/dev/null 2>&1 
        fi

        chcon -t modules_object_t $SDK_HOME/driver/pcie/*.ko >/dev/null 2>&1

        if [ -f $SDK_HOME/driver/pcie/load.sh ]; then
                bash $SDK_HOME/driver/pcie/load.sh >/dev/null 2>&1
        fi
}

# Stop the Driver Server
stop()
{
        if [ -f $SDK_HOME/driver/pcie/unload.sh ]; then
                bash $SDK_HOME/driver/pcie/unload.sh >/dev/null 2>&1
        fi
}

restart() 
{
	stop
	sleep 1
	start	
	return 0
}

# Main logic
case "$1" in
    start)
        start
    ;;
    stop)
	stop
    ;;
    restart)
	restart
        ;;
  *)
    echo $"Usage: $0 {start}"
    exit 1
esac
exit 0
