#!/bin/bash

start_managevirnic()
{
	card_type=`lspci -vv | grep "Subsystem: Device 10ee" | awk '{print $3}'`
    if [ $card_type == "10ee:2147" ] && [ -f "/opt/MVS/driver/pcie/manage_virnic" ] ; then
		declare -a mvfg_interfaces
		mvfg_interfaces=($(ifconfig -a | grep -o '^mvfg[^: ]*'))

		echo 10485760 > /proc/sys/net/core/wmem_default
		echo 10485760 > /proc/sys/net/core/wmem_max
		echo 10485760 > /proc/sys/net/core/rmem_default
		echo 10485760 > /proc/sys/net/core/rmem_max

		nohup /opt/MVS/driver/pcie/manage_virnic ${mvfg_interfaces[0]} ${mvfg_interfaces[1]} ${mvfg_interfaces[2]} ${mvfg_interfaces[3]} > /dev/null 2>&1 &
		ifconfig ${mvfg_interfaces[0]} up
		ifconfig ${mvfg_interfaces[1]} up
		ifconfig ${mvfg_interfaces[2]} up
		ifconfig ${mvfg_interfaces[3]} up
	fi
}

stop_managevirnic()
{
	card_type=`lspci -vv | grep "Subsystem: Device 10ee" | awk '{print $3}'`
    if [ $card_type == "10ee:2147" ] && [ -f "/opt/MVS/driver/pcie/manage_virnic" ] ; then
		killall manage_virnic
	fi
}

case "$1" in
	start)
		echo -n "starting ManageVirNic... "
		start_managevirnic
		echo "done."
		;;
	stop)
		echo -n "stoping ManageVirNic... "
		stop_managevirnic || true
		echo "done."
		;;
	restart|reload)
		echo -n "stoping ManageVirNic... "
		stop_managevirnic && sleep .3
		echo "done."

		echo -n "starting ManageVirNic... "
		start_managevirnic
		echo "done."
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
