#!/usr/bin/env python3
"""
npz_to_heightgrid.py
Convert the high-density ground_surface_dense.npz (0.01m grid, 4.78M cells,
generated by tools/extract_field_surface.py) to the compact .bin format
used by the C++ HeightGrid class for O(1) ray-surface intersection.

Usage:
    cd /home/zst/T
    .venv/bin/python tools/npz_to_heightgrid.py

Output: config/map/field_mesh.bin  (~19 MB, 0.01m resolution)
        10× more accurate than gen_field_mesh.py (0.1m grid)
"""
import argparse
import os
import struct
import numpy as np


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input",  default="config/outputs/ground_surface_dense.npz")
    ap.add_argument("--output", default="config/map/field_mesh.bin")
    ap.add_argument("--clamp-floor", type=float, default=0.0,
                    help="Clamp Z values below this to this value (robots stand on Z>=0)")
    args = ap.parse_args()

    print(f"[npz_to_heightgrid] Loading {args.input} ...")
    d = np.load(args.input)
    X = d['X']   # shape (ny, nx) float64
    Y = d['Y']
    Z = d['Z'].astype(np.float32)

    ny, nx = Z.shape
    x_min = float(X[0, 0])
    y_min = float(Y[0, 0])
    res_x = float((X[0, -1] - X[0, 0]) / (nx - 1))
    res_y = float((Y[-1, 0] - Y[0, 0]) / (ny - 1))

    assert abs(res_x - res_y) < 1e-6, f"Non-square grid: res_x={res_x} res_y={res_y}"
    res = (res_x + res_y) / 2.0

    valid = (~np.isnan(Z)).sum()
    print(f"  Grid   : {nx}×{ny}  res={res*100:.1f}cm")
    print(f"  Valid  : {valid:,} / {Z.size:,} ({100*valid/Z.size:.1f}%)")
    print(f"  X      : [{x_min:.3f}, {X[0,-1]:.3f}] m")
    print(f"  Y      : [{y_min:.3f}, {Y[-1,0]:.3f}] m")
    print(f"  Z(raw) : [{np.nanmin(Z):.4f}, {np.nanmax(Z):.4f}] m")

    # Clamp negative Z to floor (robots can't be below the playing surface)
    below_floor = (~np.isnan(Z)) & (Z < args.clamp_floor)
    Z[below_floor] = args.clamp_floor
    print(f"  Z clamped {below_floor.sum():,} cells below {args.clamp_floor}m to floor")
    print(f"  Z(final): [{np.nanmin(Z):.4f}, {np.nanmax(Z):.4f}] m")

    # Write .bin:  header (6×float64) + z_grid (ny×nx float32, row-major)
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    header = struct.pack("6d", x_min, y_min, float(nx), float(ny), res, 0.0)
    z_flat = Z.flatten()  # already float32, row-major
    with open(args.output, "wb") as f:
        f.write(header)
        f.write(z_flat.tobytes())

    size_mb = os.path.getsize(args.output) / 1024 / 1024
    print(f"[npz_to_heightgrid] Saved → {args.output}  ({size_mb:.1f} MB)")
    print()
    print("Add to radar_runtime.yaml → resolve section:")
    print(f"  field_grid_path: \"{args.output}\"")
    print()
    print("Accuracy vs previous 0.1m grid:")
    print(f"  Resolution : 0.10m → {res*100:.1f}cm  (10× better Z accuracy)")
    print(f"  XY error   : ≤5cm  → ≤{res*50:.0f}mm  (per grid cell)")


if __name__ == "__main__":
    main()
